apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "surf-companion.fullname" . }}-config
  labels:
    {{- include "surf-companion.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  PORT: {{ .Values.backend.port | quote }}
